--Test Data Insertion into supplier table
USE [Portfolio Projects]
-- First create a temp table with real supplier names
CREATE TABLE #supplier_names (id INT IDENTITY(1,1), name VARCHAR(100), country VARCHAR(50))

INSERT INTO #supplier_names (name, country) VALUES
('Samsung Electronics', 'South Korea'),
('LG Corporation', 'South Korea'),
('Sony Group', 'Japan'),
('Apple Inc', 'United States'),
('Nike Inc', 'United States'),
('Adidas AG', 'Germany'),
('Unilever', 'United Kingdom'),
('Nestle SA', 'Switzerland'),
('Procter and Gamble', 'United States'),
('Dangote Industries', 'Nigeria'),
('Innoson Motors', 'Nigeria'),
('Chi Limited', 'Nigeria'),
('Honeywell Flour Mills', 'Nigeria'),
('Cadbury Nigeria', 'Nigeria'),
('Guinness Nigeria', 'Nigeria'),
('PZ Cussons', 'United Kingdom'),
('Reckitt Benckiser', 'United Kingdom'),
('Philips Electronics', 'Netherlands'),
('Panasonic', 'Japan'),
('HP Inc', 'United States'),
('Dell Technologies', 'United States'),
('Lenovo Group', 'China'),
('Huawei Technologies', 'China'),
('Xiaomi Corporation', 'China'),
('Tecno Mobile', 'China'),
('Itel Mobile', 'China'),
('Infinix Mobile', 'China'),
('Jumia Technologies', 'Nigeria'),
('Konga Online Shopping', 'Nigeria'),
('Shoprite Holdings', 'South Africa'),
('Puma SE', 'Germany'),
('Reebok', 'United States'),
('Under Armour', 'United States'),
('Zara SA', 'Spain'),
('HM Group', 'Sweden'),
('Primark', 'Ireland'),
('Colgate Palmolive', 'United States'),
('Johnson and Johnson', 'United States'),
('GlaxoSmithKline', 'United Kingdom'),
('May and Baker Nigeria', 'Nigeria'),
('Emzor Pharmaceutical', 'Nigeria'),
('Vitafoam Nigeria', 'Nigeria'),
('Nigerian Breweries', 'Nigeria'),
('Seven Up Bottling', 'Nigeria'),
('Coca Cola Nigeria', 'Nigeria'),
('Pepsi Cola Nigeria', 'Nigeria'),
('Dufil Prima Foods', 'Nigeria'),
('Flour Mills Nigeria', 'Nigeria'),
('UAC Foods', 'Nigeria'),
('BASF Nigeria', 'Germany'),
('3M Company', 'United States'),
('Bosch GmbH', 'Germany'),
('Siemens AG', 'Germany'),
('ABB Ltd', 'Switzerland'),
('Schneider Electric', 'France'),
('Caterpillar Inc', 'United States'),
('Michelin', 'France'),
('Bridgestone', 'Japan'),
('Dunlop Nigeria', 'Nigeria'),
('Toyota Nigeria', 'Japan'),
('Honda Nigeria', 'Japan'),
('Ford Motor', 'United States'),
('Hyundai Motor', 'South Korea'),
('Kia Motors', 'South Korea'),
('Suzuki Motor', 'Japan'),
('Yamaha Motor', 'Japan'),
('Canon Inc', 'Japan'),
('Nikon Corporation', 'Japan'),
('Epson', 'Japan'),
('Brother Industries', 'Japan'),
('Toshiba', 'Japan'),
('Hitachi', 'Japan'),
('Fujifilm', 'Japan'),
('Olympus Corporation', 'Japan'),
('ASUS', 'Taiwan'),
('Acer Inc', 'Taiwan'),
('MSI', 'Taiwan'),
('Intel Corporation', 'United States'),
('AMD', 'United States'),
('Nvidia', 'United States'),
('Western Digital', 'United States'),
('Seagate Technology', 'United States'),
('Kingston Technology', 'United States'),
('Corsair Gaming', 'United States'),
('Logitech', 'Switzerland'),
('Razer Inc', 'United States'),
('Belkin International', 'United States'),
('Anker Innovations', 'China'),
('Oraimo', 'China'),
('Polystar Nigeria', 'Nigeria'),
('Binatone', 'United Kingdom'),
('Thermocool', 'Nigeria'),
('Nexus', 'Nigeria'),
('Scanfrost', 'Nigeria'),
('Haier Thermocool', 'China'),
('Hisense Nigeria', 'China'),
('Skyworth', 'China'),
('Syinix', 'China'),
('Royal Philips', 'Netherlands'),
('Black and Decker', 'United States'),
('Kenwood', 'United Kingdom');

INSERT INTO suppliers (supplier_name, country, contact_email)
SELECT 
    name,
    country,
    LOWER(REPLACE(name, ' ', '.')) + '@business.com'
FROM #supplier_names;

DROP TABLE #supplier_names;

Select top 10 * from Suppliers